# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

references:
  node_deps_cache_key: &node_deps_cache_key v1-dependencies-{{ checksum "package.json" }}
  node_deps_backup_cache_key: &node_deps_backup_cache_key v1-dependencies-{{ checksum "package.json" }}
  workspace_root: &workspace_root /tmp/workspace
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

executors:
  my-executor:
    docker:
      - image: circleci/node:10.11.0
    working_directory: ~/repos

jobs:
  build:
    executor: my-executor
    steps:
      - *attach_workspace
      - checkout
      - restore_cache:
          keys:
            - *node_deps_cache_key
            - *node_deps_backup_cache_key
      - run: npm install
      - run: npm test
      - run: npm run build

      - persist_to_workspace:
        root: *workspace_root
        paths:
          - build

      - save_cache:
          key: *node_deps_cache_key
          paths:
            - node_modules

  deploy-prod:
    executor: my-executor
    steps:
      - *attach_workspace
      - run:
          name: Deploy Master to Firebase
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN

workflows:
  version: 2.1
  build-deploy:
    jobs:
      - build
      - deploy-prod:
          requires:
            - build
          filters:
            branches:
              only: master
      # - deploy-stage:
      #     requires:
      #       - build
      #     filters:
      #       branches:
      #         only: staging
